
#line 3 "lex.yy.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5
#define YY_FLEX_SUBMINOR_VERSION 39
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

#ifdef __cplusplus

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

/* C99 requires __STDC__ to be defined as 1. */
#if defined (__STDC__)

#define YY_USE_CONST

#endif	/* defined (__STDC__) */
#endif	/* ! __cplusplus */

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart(yyin  )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#define YY_BUF_SIZE 16384
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern yy_size_t yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

    #define YY_LESS_LINENO(n)
    #define YY_LINENO_REWIND_TO(ptr)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	yy_size_t yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */
    
	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = 0; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)

/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static yy_size_t yy_n_chars;		/* number of characters read into yy_ch_buf */
yy_size_t yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart (FILE *input_file  );
void yy_switch_to_buffer (YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer (FILE *file,int size  );
void yy_delete_buffer (YY_BUFFER_STATE b  );
void yy_flush_buffer (YY_BUFFER_STATE b  );
void yypush_buffer_state (YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state (void );

static void yyensure_buffer_stack (void );
static void yy_load_buffer_state (void );
static void yy_init_buffer (YY_BUFFER_STATE b,FILE *file  );

#define YY_FLUSH_BUFFER yy_flush_buffer(YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer (char *base,yy_size_t size  );
YY_BUFFER_STATE yy_scan_string (yyconst char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes (yyconst char *bytes,yy_size_t len  );

void *yyalloc (yy_size_t  );
void *yyrealloc (void *,yy_size_t  );
void yyfree (void *  );

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer(yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer(yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

typedef unsigned char YY_CHAR;

FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;

typedef int yy_state_type;

extern int yylineno;

int yylineno = 1;

extern char *yytext;
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state (void );
static yy_state_type yy_try_NUL_trans (yy_state_type current_state  );
static int yy_get_next_buffer (void );
static void yy_fatal_error (yyconst char msg[]  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (size_t) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;

#define YY_NUM_RULES 29
#define YY_END_OF_BUFFER 30
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static yyconst flex_int16_t yy_accept[401] =
    {   0,
        0,    0,   30,   29,   29,   29,   21,   29,   29,   29,
       23,    0,    0,    0,    0,    0,    0,    0,    0,    0,
       21,   21,    0,    0,    0,    0,    0,   27,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,   21,   21,   28,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,

       26,    0,   15,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,   15,   15,    0,    0,    0,   10,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,   15,   15,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,   22,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    1,    0,    0,    0,
        2,    0,    0,    0,    0,    0,    0,   11,    0,    0,

        0,    0,    0,    0,    0,    0,    0,    4,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    5,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    3,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,   14,   25,
        0,    0,    0,    0,    6,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,

        0,   20,    0,    0,    0,    0,    0,    0,    0,    0,
       18,    0,    0,    0,   13,    0,    0,    0,    0,    0,
        0,    0,    0,   19,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    7,    0,    0,   13,
        0,    0,    0,   24,    0,    0,   17,    9,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    8,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,   16,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,   12,    0,    0,    0

    } ;

static yyconst flex_int32_t yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    2,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    3,    1,    1,    1,    1,    4,    5,    3,    1,
        1,    1,    1,    6,    1,    7,    1,    8,    8,    8,
        8,    8,    8,    8,    8,    9,    8,    6,    6,    1,
       10,    1,    1,    1,    6,    6,    6,    6,    6,    6,
        6,    6,    6,    6,    6,    6,    6,    6,    6,    6,
        6,    6,    6,    6,    6,    6,    6,    6,    6,    6,
       11,   12,   13,    1,    1,    1,   14,   15,   16,   17,

       18,   19,   20,   21,   22,    6,   23,   24,   25,   26,
       27,   28,    6,   29,   30,   31,   32,    6,   33,   34,
        6,   35,   36,    6,   37,    1,    1,    6,    6,    6,
        1,    6,    1,    1,    6,    6,    6,    6,    6,    6,
        6,    6,    6,    1,    6,    6,    6,    6,    1,    6,
        1,    1,    6,    6,    1,    6,    1,    1,    1,    6,
        6,    6,    1,    6,    1,    1,    6,    6,    6,    6,
        6,    6,    6,    6,    6,    1,    6,    6,    6,    6,
        1,    6,    1,    1,    6,    6,    6,    6,    1,    1,
        1,    1,    1,    1,    6,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst flex_int32_t yy_meta[38] =
    {   0,
        1,    2,    3,    1,    4,    5,    5,    3,    3,    1,
        1,    6,    7,    5,    5,    5,    5,    5,    5,    5,
        5,    5,    5,    5,    5,    5,    5,    5,    5,    5,
        5,    5,    5,    5,    5,    8,    8
    } ;

static yyconst flex_int16_t yy_base[444] =
    {   0,
        0,   37, 1006, 1007,   12,   14,   21,   48,   50,   63,
       25,   58,   61,   80,   93,  100,  107,  114,  993,   68,
       83,  121,  128,  135,  142,  150,   31, 1007,  986,  982,
      975,  975,   75,   80,    0,   50,  131,  161,  163,  165,
      173,  175,  183,  190,  197,  200, 1007,  980,  985,  982,
      979,  971,  974,  974,  969,  968,  967,  945,  945,  956,
      946,  951,  208,  945,  936,  931,   18,  935,  939,  932,
      928,  919,  917,  914,  918,  921,   77,  910,  910,  902,
      907,  103,  899,  909,  892,   41,  899,  100,   75,  900,
      886,    0,  898,   91,  893,  891,  121,  880,  874,  889,

     1007,  883,  204,  211,  872,  881,  879,  872,  859,  105,
      864,  143,  869,  204,  853,  853,  853,  848,  860,  841,
      852,  852,  847,  220,  222,  224,  231,  233,  235, 1007,
      836,  828,  826,  151,  160,  242,  831,  216,  825,  229,
      819,  807,  811,  218,  791,  805,  786,  790,  789,  781,
      792,  254,  256,  258,  267,  232,  789,  790,  274,  278,
      281,  285,  288, 1007,  781,  292,  792,  775,  788,  771,
      784,  786,  295,  784,  768,  769,  769,  758,  753,  743,
      299,  738,  743,  309,  330,  334, 1007,  337,  341,  344,
     1007,  348,  351,  724,  355,  365,  383, 1007,  711,  713,

      695,  697,  694,  675,  386,  390,  397, 1007,  678,  679,
      674,  645,  638,  657,  648,  400,  404,  407, 1007,  634,
      627,  414,  421,  428,  439,  236,  446,  453,  635,  621,
      616,  620,  601,  597,  460,  463,  593,  567,  558,  568,
      561,  535,  533,  470,  477,  269,  507,  484,  466,  504,
      497,  479,  470,  487,  468,  460,  457,  450,  437,  283,
      449,  501,  440,  508,  515,  519, 1007,  522,    0,  407,
      406,  414,  407,  392,  388,  392,  374,  386, 1007, 1007,
      368,  531,  533,  540, 1007,  353,  550,  554,  557,  565,
      572,  290,  580,  325,  341,  338,  334,  318,  339,  508,

      321, 1007,  304,  318,  589,  591,  346,  593,  600,  611,
     1007,  308,  286,  298, 1007,  360,  609,    0,  287,  279,
      607,  626,  272, 1007,  255,  628,  637,  639,  646,  402,
      409,  248,  263,  648,  658,  660, 1007,  667,  234,  247,
      669,  676,  678, 1007,  680,  695, 1007, 1007,  216,  697,
      708,  416,  200,  715,  717,  727,  196,  193, 1007,  729,
      738,  747,  187,  458,  749,  758,  170,  654,  173,  535,
      179,  712,  451,  703,  761,  673,  538,  766,  125,  496,
      134,  568,  115, 1007,  115,  102,   85,   83,   34,   10,
       12,  596,  773,  776,  780,  783, 1007,  787,  790, 1007,

      827,  834,  837,  841,  844,  849,  852,  855,   11,  858,
      861,  866,  869,  872,  878,  884,  890,  893,  899,  905,
      911,  914,  917,  920,  923,  926,  932,  938,  941,    2,
      946,  949,  952,    1,  957,  963,  969,  972,  975,  978,
      983,  986,  992
    } ;

static yyconst flex_int16_t yy_def[444] =
    {   0,
      401,  401,  400,  400,  402,  403,  404,  405,  405,  400,
      406,  407,  402,  406,  403,  405,  405,  405,  400,  408,
      404,  404,  403,  405,  405,  403,  400,  400,  400,  400,
      400,  400,  400,  400,  400,  400,  400,  406,  406,  406,
      406,  406,  406,  405,  404,  404,  400,  400,  400,  400,
      400,  400,  400,  400,  400,  400,  400,  400,  400,  400,
      400,  400,  406,  400,  400,  400,  400,  400,  400,  400,
      400,  400,  400,  400,  400,  400,  400,  400,  400,  400,
      400,  400,  400,  400,  400,  400,  400,  400,  400,  400,
      400,  409,  400,  400,  400,  400,  400,  400,  400,  400,

      400,  400,  410,  411,  400,  400,  400,  400,  400,  400,
      400,  409,  400,  400,  400,  400,  400,  400,  400,  400,
      400,  400,  400,  412,  410,  410,  413,  411,  411,  400,
      400,  400,  400,  400,  400,  414,  400,  400,  400,  400,
      400,  400,  400,  400,  400,  400,  400,  400,  400,  400,
      400,  410,  410,  411,  411,  400,  400,  400,  415,  416,
      417,  414,  414,  400,  400,  418,  400,  400,  400,  400,
      400,  400,  419,  400,  400,  400,  400,  400,  400,  400,
      420,  400,  400,  421,  415,  415,  400,  422,  416,  416,
      400,  414,  414,  400,  423,  418,  418,  400,  400,  400,

      400,  400,  400,  400,  424,  419,  419,  400,  400,  400,
      400,  400,  400,  400,  400,  425,  420,  420,  400,  400,
      400,  415,  415,  416,  416,  400,  418,  418,  400,  400,
      400,  400,  400,  400,  419,  419,  400,  400,  400,  400,
      400,  400,  400,  420,  420,  400,  400,  426,  400,  400,
      400,  400,  400,  400,  400,  400,  400,  400,  400,  400,
      400,  427,  400,  428,  426,  426,  400,  429,  430,  400,
      400,  400,  400,  400,  400,  400,  400,  400,  400,  400,
      400,  431,  427,  427,  400,  400,  426,  426,  432,  429,
      429,  400,  429,  430,  400,  400,  400,  400,  400,  400,

      400,  400,  400,  400,  427,  427,  400,  429,  429,  429,
      400,  400,  400,  400,  400,  400,  433,  434,  400,  400,
      435,  429,  400,  400,  400,  436,  437,  433,  433,  400,
      434,  400,  400,  438,  435,  435,  400,  429,  400,  400,
      439,  436,  436,  400,  433,  433,  400,  400,  400,  435,
      435,  400,  400,  440,  436,  436,  400,  430,  400,  441,
      440,  440,  400,  430,  440,  440,  400,  430,  400,  430,
      400,  430,  400,  430,  400,  430,  400,  400,  400,  430,
      400,  430,  400,  400,  400,  400,  400,  400,  400,  400,
      400,  400,  442,  443,  442,  442,  400,  442,  442,    0,

      400,  400,  400,  400,  400,  400,  400,  400,  400,  400,
      400,  400,  400,  400,  400,  400,  400,  400,  400,  400,
      400,  400,  400,  400,  400,  400,  400,  400,  400,  400,
      400,  400,  400,  400,  400,  400,  400,  400,  400,  400,
      400,  400,  400
    } ;

static yyconst flex_int16_t yy_nxt[1045] =
    {   0,
        4,    5,    6,    7,    4,  331,  294,    9,    9,    4,
        4,   10,    4,   11,   12,  112,   15,   56,   16,   14,
       14,   18,   18,   20,  392,   19,   11,   12,   22,   22,
      391,   57,   39,   39,   47,    4,    4,    4,    5,    6,
        7,    4,   28,  103,    9,    9,    4,    4,   10,    4,
       23,  104,   26,   82,   83,   25,   25,   25,   25,   19,
       12,   27,   11,   12,  390,   41,   41,   58,   14,   14,
       20,   59,    4,    4,   28,   46,   46,   29,   30,   31,
       32,   11,   12,   33,   34,   20,   42,   43,   43,  108,
       22,   22,   35,   36,   37,   15,  109,  400,   52,  389,

       18,   18,   44,   53,  400,   54,  388,   25,   25,   23,
       55,   19,   92,   92,   25,   25,   23,  106,   19,   97,
       98,   25,   25,   20,   99,   19,  114,  115,   22,   22,
       15,  107,   16,  100,  387,   18,   18,   23,  118,   19,
      136,  136,   25,   25,   23,  386,   19,  119,  385,   25,
       25,  383,   15,   19,   16,  381,   60,   18,   18,   61,
       62,   27,   11,   12,   11,   12,   11,   12,   39,   39,
       39,   39,   39,   39,   11,   12,   11,   12,  138,  138,
       39,   39,   63,   63,   11,   12,  159,  159,  373,   42,
       63,   63,   23,  371,   16,  160,  160,   25,   25,   20,

      369,   19,   20,  367,   22,   22,  124,   22,   22,   11,
       12,  126,  126,  127,  364,   63,   63,  363,  129,  129,
      140,  141,  124,  130,  124,  142,  124,  153,  153,  126,
      126,  126,  126,  127,  143,  127,  359,  127,  155,  155,
      129,  129,  129,  129,  161,  130,  168,  130,  357,  163,
      163,  166,  166,  173,  173,  169,  124,  354,  124,  353,
      127,  126,  126,  126,  126,  129,  129,  181,  181,  127,
      130,  248,  248,  349,  129,  129,  184,  164,  164,  130,
      188,  186,  186,  161,  348,  190,  190,  161,  193,  193,
      161,  340,  163,  163,  195,  163,  163,  205,  339,  197,

      197,  216,  207,  207,  262,  262,  218,  218,  333,  187,
      187,  184,  332,  191,  191,  325,  223,  223,  280,  280,
      164,  164,  324,  164,  164,  269,  269,  198,  198,  323,
      208,  208,  184,  320,  219,  219,  184,  186,  186,  188,
      279,  186,  186,  188,  225,  225,  188,  319,  190,  190,
      161,  190,  190,  161,  315,  163,  163,  195,  163,  163,
      311,  311,  228,  228,  314,  187,  187,  195,  313,  187,
      187,  312,  197,  197,  316,  316,  191,  191,  307,  191,
      191,  321,  321,  164,  164,  195,  164,  164,  205,  304,
      197,  197,  205,  236,  236,  326,  326,  207,  207,  205,

      198,  198,  216,  303,  207,  207,  216,  245,  245,  216,
      302,  218,  218,  301,  218,  218,  184,  300,  198,  198,
      299,  186,  186,  184,  298,  208,  208,  297,  186,  186,
      188,  296,  208,  208,  295,  190,  190,  318,  318,  219,
      219,  188,  219,  219,  347,  347,  190,  190,  195,  187,
      187,  358,  269,  197,  197,  195,  187,  187,  375,  375,
      197,  197,  205,  191,  191,  205,  286,  207,  207,  281,
      207,  207,  216,  279,  191,  191,  268,  218,  218,  216,
      278,  198,  198,  368,  218,  218,  264,  277,  198,  198,
      276,  266,  266,  311,  311,  208,  208,  275,  208,  208,

      274,  269,  269,  282,  273,  219,  219,  272,  284,  284,
      264,  382,  219,  219,  271,  288,  288,  264,  317,  267,
      267,  264,  266,  266,  289,  270,  266,  266,  263,  291,
      291,  311,  311,  282,  292,  282,  285,  285,  306,  306,
      284,  284,  282,  318,  318,  378,  378,  284,  284,  379,
      267,  267,  264,  293,  267,  267,  264,  266,  266,  289,
      261,  266,  266,  260,  309,  309,  372,  289,  285,  285,
      311,  311,  291,  291,  289,  285,  285,  292,  259,  291,
      291,  258,  289,  257,  292,  267,  267,  291,  291,  267,
      267,  282,  292,  282,  256,  289,  284,  284,  284,  284,

      291,  291,  289,  311,  384,  292,  255,  291,  291,  334,
      310,  327,  292,  289,  336,  336,  329,  329,  291,  291,
      254,  330,  253,  292,  285,  285,  285,  285,  289,  322,
      341,  393,  393,  291,  338,  343,  343,  252,  292,  327,
      251,  327,  337,  337,  346,  346,  329,  329,  327,  250,
      334,  330,  249,  329,  329,  351,  351,  247,  330,  246,
      334,  243,  334,  344,  344,  336,  336,  336,  336,  289,
      242,  341,  241,  240,  291,  291,  356,  356,  341,  352,
      341,  370,  327,  343,  343,  343,  343,  329,  329,  311,
      311,  239,  330,  337,  337,  337,  337,  327,  380,  334,

      238,  237,  329,  329,  336,  336,  234,  330,  311,  311,
      334,  344,  344,  344,  344,  336,  336,  360,  233,  341,
      376,  232,  362,  362,  343,  343,  231,  315,  230,  341,
      229,  360,  337,  337,  343,  343,  366,  366,  311,  311,
      360,  226,  374,  337,  337,  362,  362,  311,  311,  360,
      315,  360,  344,  344,  362,  362,  362,  362,  221,  315,
      360,  315,  344,  344,  220,  362,  362,  377,  378,  378,
      315,  215,  379,  378,  378,  394,  214,  379,  394,  213,
      396,  396,  394,  399,  399,  394,  212,  396,  396,  394,
      396,  396,  394,  211,  396,  396,  210,  396,  396,  209,

      204,  203,  202,  201,  200,  199,  194,  183,  397,  397,
      182,  180,  179,  178,  177,  397,  397,  176,  397,  397,
      175,  174,  397,  397,  172,  397,  397,    8,    8,    8,
        8,    8,    8,    8,    8,   13,   13,  171,   13,   17,
       17,   17,   17,   21,  170,   21,   24,  167,   24,   24,
       38,   38,  165,   38,   40,  158,   40,   45,  157,   45,
      125,  156,  125,  128,  151,  128,  150,  128,  152,  149,
      152,  154,  148,  154,  162,  147,  162,  146,  145,  162,
      185,  144,  185,  143,  139,  185,  189,  137,  189,  135,
      134,  189,  192,  133,  192,  196,  132,  196,  131,  123,

      196,  206,  122,  206,  121,  120,  206,  217,  117,  217,
      116,  113,  217,  222,  111,  222,  224,  110,  224,  227,
      105,  227,  235,  102,  235,  244,  101,  244,  265,  100,
      265,   96,   95,  265,  283,   94,  283,   93,   91,  283,
      287,   90,  287,  290,   89,  290,   88,  290,  305,   87,
      305,  308,   86,  308,  328,   85,  328,   77,  328,  335,
       84,  335,   81,   80,  335,  342,   79,  342,   78,   77,
      342,  345,   76,  345,  350,   75,  350,  355,   74,  355,
      361,   73,  361,   72,  361,  365,   71,  365,  395,   70,
      395,   69,   68,  395,  398,   67,  398,   66,   65,   64,

       51,   50,   49,   48,   28,  400,    3,  400,  400,  400,
      400,  400,  400,  400,  400,  400,  400,  400,  400,  400,
      400,  400,  400,  400,  400,  400,  400,  400,  400,  400,
      400,  400,  400,  400,  400,  400,  400,  400,  400,  400,
      400,  400,  400,  400
    } ;

static yyconst flex_int16_t yy_chk[1045] =
    {   0,
        1,    1,    1,    1,    1,  434,  430,    1,    1,    1,
        1,    1,    1,    5,    5,  409,    6,   35,    6,    5,
        5,    6,    6,    7,  391,    6,   11,   11,    7,    7,
      390,   35,   11,   11,   27,    1,    1,    2,    2,    2,
        2,    2,   27,   86,    2,    2,    2,    2,    2,    2,
        8,   86,    9,   67,   67,    8,    8,    9,    9,    8,
       12,    9,   13,   13,  389,   12,   12,   36,   13,   13,
       20,   36,    2,    2,   10,   20,   20,   10,   10,   10,
       10,   14,   14,   10,   10,   21,   14,   14,   14,   89,
       21,   21,   10,   10,   10,   15,   89,   15,   33,  388,

       15,   15,   16,   33,   15,   34,  387,   16,   16,   17,
       34,   16,   77,   77,   17,   17,   18,   88,   17,   82,
       82,   18,   18,   22,   82,   18,   94,   94,   22,   22,
       23,   88,   23,   82,  386,   23,   23,   24,   97,   23,
      110,  110,   24,   24,   25,  385,   24,   97,  383,   25,
       25,  381,   26,   25,   26,  379,   37,   26,   26,   37,
       37,   26,   38,   38,   39,   39,   40,   40,   38,   38,
       39,   39,   40,   40,   41,   41,   42,   42,  112,  112,
       41,   41,   42,   42,   43,   43,  134,  134,  371,   43,
       43,   43,   44,  369,   44,  135,  135,   44,   44,   45,

      367,   44,   46,  363,   45,   45,  103,   46,   46,   63,
       63,  103,  103,  104,  358,   63,   63,  357,  104,  104,
      114,  114,  124,  104,  125,  114,  126,  124,  124,  125,
      125,  126,  126,  127,  114,  128,  353,  129,  127,  127,
      128,  128,  129,  129,  136,  128,  140,  129,  349,  136,
      136,  138,  138,  144,  144,  140,  152,  340,  153,  339,
      154,  152,  152,  153,  153,  154,  154,  156,  156,  155,
      154,  226,  226,  333,  155,  155,  159,  136,  136,  155,
      160,  159,  159,  161,  332,  160,  160,  162,  161,  161,
      163,  325,  162,  162,  166,  163,  163,  173,  323,  166,

      166,  181,  173,  173,  246,  246,  181,  181,  320,  159,
      159,  184,  319,  160,  160,  314,  184,  184,  260,  260,
      162,  162,  313,  163,  163,  292,  292,  166,  166,  312,
      173,  173,  185,  304,  181,  181,  186,  185,  185,  188,
      303,  186,  186,  189,  188,  188,  190,  301,  189,  189,
      192,  190,  190,  193,  298,  192,  192,  195,  193,  193,
      294,  294,  195,  195,  297,  185,  185,  196,  296,  186,
      186,  295,  196,  196,  299,  299,  189,  189,  286,  190,
      190,  307,  307,  192,  192,  197,  193,  193,  205,  281,
      197,  197,  206,  205,  205,  316,  316,  206,  206,  207,

      196,  196,  216,  278,  207,  207,  217,  216,  216,  218,
      277,  217,  217,  276,  218,  218,  222,  275,  197,  197,
      274,  222,  222,  223,  273,  206,  206,  272,  223,  223,
      224,  271,  207,  207,  270,  224,  224,  330,  330,  217,
      217,  225,  218,  218,  331,  331,  225,  225,  227,  222,
      222,  352,  352,  227,  227,  228,  223,  223,  373,  373,
      228,  228,  235,  224,  224,  236,  263,  235,  235,  261,
      236,  236,  244,  259,  225,  225,  249,  244,  244,  245,
      258,  227,  227,  364,  245,  245,  248,  257,  228,  228,
      256,  248,  248,  364,  364,  235,  235,  255,  236,  236,

      254,  249,  249,  262,  253,  244,  244,  252,  262,  262,
      264,  380,  245,  245,  251,  264,  264,  265,  300,  248,
      248,  266,  265,  265,  268,  250,  266,  266,  247,  268,
      268,  380,  380,  282,  268,  283,  262,  262,  282,  282,
      283,  283,  284,  300,  300,  377,  377,  284,  284,  377,
      265,  265,  287,  268,  266,  266,  288,  287,  287,  289,
      243,  288,  288,  242,  289,  289,  370,  290,  283,  283,
      370,  370,  290,  290,  291,  284,  284,  290,  241,  291,
      291,  240,  293,  239,  291,  287,  287,  293,  293,  288,
      288,  305,  293,  306,  238,  308,  305,  305,  306,  306,

      308,  308,  309,  382,  382,  308,  237,  309,  309,  321,
      293,  317,  309,  310,  321,  321,  317,  317,  310,  310,
      234,  317,  233,  310,  305,  305,  306,  306,  322,  310,
      326,  392,  392,  322,  322,  326,  326,  232,  322,  327,
      231,  328,  321,  321,  327,  327,  328,  328,  329,  230,
      334,  328,  229,  329,  329,  334,  334,  221,  329,  220,
      335,  215,  336,  326,  326,  335,  335,  336,  336,  338,
      214,  341,  213,  212,  338,  338,  341,  341,  342,  338,
      343,  368,  345,  342,  342,  343,  343,  345,  345,  368,
      368,  211,  345,  335,  335,  336,  336,  346,  376,  350,

      210,  209,  346,  346,  350,  350,  204,  346,  376,  376,
      351,  342,  342,  343,  343,  351,  351,  354,  203,  355,
      374,  202,  354,  354,  355,  355,  201,  354,  200,  356,
      199,  360,  350,  350,  356,  356,  360,  360,  374,  374,
      361,  194,  372,  351,  351,  361,  361,  372,  372,  362,
      361,  365,  355,  355,  362,  362,  365,  365,  183,  362,
      366,  365,  356,  356,  182,  366,  366,  375,  375,  375,
      366,  180,  375,  378,  378,  393,  179,  378,  394,  178,
      393,  393,  395,  394,  394,  396,  177,  395,  395,  398,
      396,  396,  399,  176,  398,  398,  175,  399,  399,  174,

      172,  171,  170,  169,  168,  167,  165,  158,  393,  393,
      157,  151,  150,  149,  148,  395,  395,  147,  396,  396,
      146,  145,  398,  398,  143,  399,  399,  401,  401,  401,
      401,  401,  401,  401,  401,  402,  402,  142,  402,  403,
      403,  403,  403,  404,  141,  404,  405,  139,  405,  405,
      406,  406,  137,  406,  407,  133,  407,  408,  132,  408,
      410,  131,  410,  411,  123,  411,  122,  411,  412,  121,
      412,  413,  120,  413,  414,  119,  414,  118,  117,  414,
      415,  116,  415,  115,  113,  415,  416,  111,  416,  109,
      108,  416,  417,  107,  417,  418,  106,  418,  105,  102,

      418,  419,  100,  419,   99,   98,  419,  420,   96,  420,
       95,   93,  420,  421,   91,  421,  422,   90,  422,  423,
       87,  423,  424,   85,  424,  425,   84,  425,  426,   83,
      426,   81,   80,  426,  427,   79,  427,   78,   76,  427,
      428,   75,  428,  429,   74,  429,   73,  429,  431,   72,
      431,  432,   71,  432,  433,   70,  433,   69,  433,  435,
       68,  435,   66,   65,  435,  436,   64,  436,   62,   61,
      436,  437,   60,  437,  438,   59,  438,  439,   58,  439,
      440,   57,  440,   56,  440,  441,   55,  441,  442,   54,
      442,   53,   52,  442,  443,   51,  443,   50,   49,   48,

       32,   31,   30,   29,   19,    3,  400,  400,  400,  400,
      400,  400,  400,  400,  400,  400,  400,  400,  400,  400,
      400,  400,  400,  400,  400,  400,  400,  400,  400,  400,
      400,  400,  400,  400,  400,  400,  400,  400,  400,  400,
      400,  400,  400,  400
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "latex2html.lex"
char word[50]; int i;
#line 822 "lex.yy.c"

#define INITIAL 0

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals (void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy (void );

int yyget_debug (void );

void yyset_debug (int debug_flag  );

YY_EXTRA_TYPE yyget_extra (void );

void yyset_extra (YY_EXTRA_TYPE user_defined  );

FILE *yyget_in (void );

void yyset_in  (FILE * in_str  );

FILE *yyget_out (void );

void yyset_out  (FILE * out_str  );

yy_size_t yyget_leng (void );

char *yyget_text (void );

int yyget_lineno (void );

void yyset_lineno (int line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap (void );
#else
extern int yywrap (void );
#endif
#endif

    static void yyunput (int c,char *buf_ptr  );
    
#ifndef yytext_ptr
static void yy_flex_strncpy (char *,yyconst char *,int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * );
#endif

#ifndef YY_NO_INPUT

#ifdef __cplusplus
static int yyinput (void );
#else
static int input (void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		size_t n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = fread(buf, 1, max_size, yyin))==0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;
    
	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer(yyin,YY_BUF_SIZE );
		}

		yy_load_buffer_state( );
		}

	{
#line 45 "latex2html.lex"

#line 1033 "lex.yy.c"

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)] ;
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 401 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 1007 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 46 "latex2html.lex"
{memcpy(&word, &yytext[8], strlen(&yytext[8])-1);
                                        printf("<b>%s</b>", word);
                                        strncpy(word, "\0", strlen(word));}
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 49 "latex2html.lex"
{memcpy(&word, &yytext[8], strlen(&yytext[8])-1);
                                        printf("<i>%s</i>", word);
                                        strncpy(word, "\0", strlen(word));}
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 52 "latex2html.lex"
{memcpy(&word, &yytext[11], strlen(&yytext[11])-1);
                                        printf("<u>%s</u>", word);
                                        strncpy(word, "\0", strlen(word));}
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 55 "latex2html.lex"
{memcpy(&word, &yytext[9], strlen(&yytext[9])-1);
                                        printf("<h1>%s</h1>",word);
                                        strncpy(word, "\0", strlen(word));}
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 58 "latex2html.lex"
{memcpy(&word, &yytext[9], strlen(&yytext[9])-1);
                                        printf("<h2>%s</h2>",word);
                                        strncpy(word, "\0", strlen(word));}
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 61 "latex2html.lex"
{memcpy(&word, &yytext[12], strlen(&yytext[12])-1);
                                        printf("<h3>%s</h3>",word);
                                        strncpy(word, "\0", strlen(word));}
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 64 "latex2html.lex"
{memcpy(&word, &yytext[15], strlen(&yytext[15])-1);
                                        printf("<h4>%s</h4>",word);
                                        strncpy(word, "\0", strlen(word));}
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 67 "latex2html.lex"
{;}
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 68 "latex2html.lex"
{;}
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 69 "latex2html.lex"
{memcpy(&word, &yytext[6], strlen(&yytext[6])-1);
                                        printf("<h5>%s</h5>", word);
                                        strncpy(word, "\0", strlen(word));}
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 72 "latex2html.lex"
{i = (yytext[1]=='u') ? 5 : 6;
                                        char * w; char * w1;
                                        w = strtok(&yytext[i],"}"); i += strlen(w)+2;
                                        w1 = strtok(&yytext[i],"}");
                                        printf("<a href=\"%s\">%s</a>", w, w1);}
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 77 "latex2html.lex"
{char * nombre; nombre = strtok(yytext,"{");
                                        nombre = strtok(NULL,"}"); 
                                        memcpy(&word, nombre, strlen(nombre));
                                        if (strstr(nombre, ".jpg") == NULL && 
                                            strstr(nombre, ".png") == NULL) {
                                            word[strlen(nombre)] = '.'; 
                                            word[strlen(nombre)+1] = '*';
                                            char aux1[] = "/bin/find . -name "; char * comando;
                                            comando = malloc(strlen(aux1) + strlen(word)+1);
                                            strcpy(comando, aux1); strcat(comando, word);
                                            FILE * p = popen(comando, "r"); char fichero[100];
                                            if(p){
                                                while(fgets(fichero, sizeof(fichero), p) != NULL){}
                                                fichero[strlen(fichero)-1] = 0;
                                                printf("<img src=\"%s\"/>", fichero);
                                            }
                                            strncpy(word, "\0", strlen(word));
                                        } else printf("<img src=\"%s\" />", word);}
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 95 "latex2html.lex"
{printf("<ul>");}
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 96 "latex2html.lex"
{printf("</ul>");}
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 97 "latex2html.lex"
{memcpy(&word, &yytext[6], strlen(&yytext[6]));
                                        printf("<li>%s</li>", word);
                                        strncpy(word, "\0", strlen(word));}
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 100 "latex2html.lex"
{printf("<meta charset=\"utf-8\">");}
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 101 "latex2html.lex"
{printf("<!DOCTYPE html>\n<html>\n<head>");}
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 102 "latex2html.lex"
{;}
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 103 "latex2html.lex"
{printf("</head>\n<body>");}
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 104 "latex2html.lex"
{printf("</body>\n</html>");}
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 105 "latex2html.lex"
{;}
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 106 "latex2html.lex"
{memcpy(&word, &yytext[7], strlen(&yytext[7])-1);
                                        printf("<title>%s</title>", word);
                                        strncpy(word, "\0", strlen(word));}
	YY_BREAK
case 23:
/* rule 23 can match eol */
YY_RULE_SETUP
#line 109 "latex2html.lex"
{printf("<p>%s</p>",yytext);}
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 110 "latex2html.lex"
{printf("<table>");}
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 111 "latex2html.lex"
{printf("</table>");}
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 112 "latex2html.lex"
{;}
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 113 "latex2html.lex"
{printf("<tr>\n"); char * fila; 
                                        fila = strtok(yytext,"&\\");
                                        while(fila != NULL){
                                            printf("<td>%s</td>\n",fila);
                                            fila = strtok(NULL,"&\\");
                                        } printf("</tr>\n");}
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 119 "latex2html.lex"
{memcpy(&word, yytext, strlen(yytext));
                                        word[strlen(yytext)] = '%'; char * text;
                                        text = strtok(word,"%");
                                        while (text != NULL){
                                            text[strlen(text)-1] = '%';
                                            printf("%s",text);
                                            text = strtok(NULL,"%");
                                        } strncpy(word, "\0", strlen(word));}
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 127 "latex2html.lex"
ECHO;
	YY_BREAK
#line 1289 "lex.yy.c"
case YY_STATE_EOF(INITIAL):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap( ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	register char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	register char *source = (yytext_ptr);
	register int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr)) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			yy_size_t num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				yy_size_t new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc((void *) b->yy_ch_buf,b->yy_buf_size + 2  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart(yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if ((yy_size_t) ((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		yy_size_t new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc((void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf,new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	register yy_state_type yy_current_state;
	register char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 401 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	register int yy_is_jam;
    	register char *yy_cp = (yy_c_buf_p);

	register YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 401 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 400);

		return yy_is_jam ? 0 : yy_current_state;
}

    static void yyunput (int c, register char * yy_bp )
{
	register char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register yy_size_t number_to_move = (yy_n_chars) + 2;
		register char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		register char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			yy_size_t offset = (yy_c_buf_p) - (yytext_ptr);
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart(yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap( ) )
						return EOF;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer(yyin,YY_BUF_SIZE );
	}

	yy_init_buffer(YY_CURRENT_BUFFER,input_file );
	yy_load_buffer_state( );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state( );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc(b->yy_buf_size + 2  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer(b,file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree((void *) b->yy_ch_buf  );

	yyfree((void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer(b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state( );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state( );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state( );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
		num_to_alloc = 1;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );
								  
		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));
				
		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		int grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object. 
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer(b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (yyconst char * yystr )
{
    
	return yy_scan_bytes(yystr,strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (yyconst char * yybytes, yy_size_t  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	yy_size_t i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = _yybytes_len + 2;
	buf = (char *) yyalloc(n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer(buf,n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yy_fatal_error (yyconst char* msg )
{
    	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
        
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
yy_size_t yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param line_number
 * 
 */
void yyset_lineno (int  line_number )
{
    
    yylineno = line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  in_str )
{
        yyin = in_str ;
}

void yyset_out (FILE *  out_str )
{
        yyout = out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  bdebug )
{
        yy_flex_debug = bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    (yy_buffer_stack) = 0;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = (char *) 0;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = (FILE *) 0;
    yyout = (FILE *) 0;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer(YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, yyconst char * s2, int n )
{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * s )
{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
	return (void *) malloc( size );
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
}

void yyfree (void * ptr )
{
	free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 127 "latex2html.lex"


yywrap()
        {return 1;}
